### PR TITLE
Soften generateKey in AggregateBy to use empty strings for missing properties instead of erroring

### PR DESCRIPTION
**Pull request by nikovacevic**
## Changes
- Soften generateKey in AggregateBy to use empty strings for missing properties instead of erroring

## Testing
- Unit testing

### CODE REVIEW

**Comment by AjayTripathy** [comment]
Looks like there is regression testing, but is it quick to write a unit test for the case where nodes are missing?

**Comment by nikovacevic** [comment]
Yep, they were just in progress :smile: Done now!

**Review by AjayTripathy — APPROVED** [review]
It LGTM but would we still want a warning when this case happens?

**Comment by nikovacevic** [comment]
Responded in Slack
> I don't think we need one, if it's now normal working-as-intended behavior.
> We'll still get logs if the node doesn't get set, but we probably don't need one on aggregation.

**Pull request merged**
