### PR TITLE
Ajay tripathy pvc error fix

### PR DESCRIPTION
**Pull request by AjayTripathy**
empty volumenames could result in many-to-many match errors, and this is potentially possible for claims that never get fulfilled.

### CODE REVIEW

**Review by dwbrown2 — COMMENTED** [review]
Could persistentvolumeclaim also be empty? If so, would that cause issues?

**Comment by AjayTripathy** [comment]
> Could persistentvolumeclaim also be empty? If so, would that cause issues?

Seems unlikely given that we're joining kube_persistentvolumeclaim_info and kube_persistentvolumeclaim_resource_requests_storage_bytes

**Review by nikovacevic — COMMENTED** [review]
I understand the query change (filtering out metrics with an empty field) but the rest I don't exactly understand. Is this a combination of two different PRs, or am I just not seeing how they relate?

Query changes LGTM.

**Comment by AjayTripathy** [comment]
> I understand the query change (filtering out metrics with an empty field) but the rest I don't exactly understand. Is this a combination of two different PRs, or am I just not seeing how they relate?
> 
> Query changes LGTM.

This branched off the wrong place, super sorry. I'll update to branch from develop

**Pull request merged**
