### PR TITLE
OSS Workflow in CONTRIBUTING

### PR DESCRIPTION
**Pull request by nealormsbee**
## What does this PR change?
Add a brief explanation of OSS contribution workflow

## Does this PR rely on any other PRs?
No

## How does this PR impact users? (This is the kind of thing that goes in release notes!)
Adds a section to CONTRIBUTING.md on the fork-PR model.

## Links to Issues or ZD tickets this PR addresses or fixes

- https://kubecost.zendesk.com/agent/tickets/1158

## How was this PR tested?
Markdown preview tool in VSCode

## Have you made an update to documentation?
This is an update to documentation

### CODE REVIEW

**Comment by nealormsbee** [comment]
Aimed at issue at a ZD issue involving confusion around this topic. Copy editing welcomed :)

**Comment by kirbsauce** [comment]
@michaelmdresser , this version is better than mine.

**Comment by nealormsbee** [comment]
I didn't realize you had one out already! I saw the ticket with your suggestion to update `CONTRIBUTING` and jumped on it

**Comment by kirbsauce** [comment]
And I very much appreciate it!!!

**Comment by nealormsbee** [comment]
I can update the emails here to be `support@kubecost`, as in the other PR.

**Comment by kirbsauce** [comment]
thanks again, @nealormsbee !

**Review by michaelmdresser — APPROVED** [review]

**Pull request merged**
