### PR TITLE
Support spec.capacity.store in InstanceIDField for CSV Provider

### PR DESCRIPTION
**Pull request by scottkarnold**
I want to be able to add hourly rate data for persistent volumes in my CSV file based on their storage capacity.

### CODE REVIEW

**Comment by michaelmdresser** [comment]
Hi @scottkarnold, thanks for opening up a PR! From a first glance it doesn't look too controversial.

Could you add a comment explaining how you tested this change?

**Comment by scottkarnold** [comment]
Here is some additional information.  A typical persistent volume spec in our environment looks something like this:

   apiVersion: v1
   kind: PersistentVolume
   metadata:
     annotations:
       pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
     name: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
     uid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
   spec:
     accessModes:
     - ReadWriteOnce
     capacity:
       storage: 25Gi
     claimRef:
       apiVersion: v1
       kind: PersistentVolumeClaim
       name: cost-analyzer
       namespace: kubecost
       uid: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
     csi:
       driver: ebs.csi.aws.com
       fsType: ext4
     nodeAffinity:
       required:
         nodeSelectorTerms:
         - matchExpressions:
           - key: topology.ebs.csi.aws.com/zone
             operator: In
             values:
             - xx-xxx-xxxx-xx
     storageClassName: ebs-csi
   status:
     phase: Released

**Comment by scottkarnold** [comment]
Listed below are the steps performed to test the requested code change.

1. Cloned the ``kubecost/cost-mode`` and``kubecost/cost-analyzer-helm-char`` git repositories to a local directory.

2. Modified ``csvprovider.go`` with the PR changes and one additional debug statement between lines 283 and 284:

``klog.Infof("storage capacity = %s", skey.String())``

3. Rebuilt the cost-model docker image, pushed it to our own docker registry, and updated ``kubecost/cost-analyzer-helm-chart/cost-analyzer/values.yaml`` to reference the new docker image.

4. Added the following persistent volume test data to our custom CSV file residing in an AWS S3 bucket:

``2021-05-01 23:34:22 UTC,1Gi,us-gov-west-1,pv,spec.capacity.storage,1Gi,0.01,``
``2021-05-01 23:34:22 UTC,2Gi,us-gov-west-1,pv,spec.capacity.storage,2Gi,0.02,``
``2021-05-01 23:34:22 UTC,5Gi,us-gov-west-1,pv,spec.capacity.storage,5Gi,0.05,``
``2021-05-01 23:34:22 UTC,10Gi,us-gov-west-1,pv,spec.capacity.storage,10Gi,0.10,``
``2021-05-01 23:34:22 UTC,25Gi,us-gov-west-1,pv,spec.capacity.storage,25Gi,0.25,``

5. Perform a helm install of Kubecost:

``$ cd kubecost/cost-analyzer-helm-chart``
``$ helm3 install cost-analyzer ./cost-analyzer``

6. Examined the logs of the ``cost-analyzer/cost-model`` container and verififie that the correct value of ``spec.capacity.storage`` was recorded via the temporary debug statement inserted in the code.

``$ kubectl logs pod/cost-analyzer-5b6885f65d-xc6lg -c cost-model | grep "storage capacity"``

``I0227 14:29:52.575104       1 csvprovider.go:284] storage capacity = 10Gi``
``I0227 14:29:52.575145       1 csvprovider.go:284] storage capacity = 1Gi``
``I0227 14:29:52.575185       1 csvprovider.go:284] storage capacity = 25Gi``
``I0227 14:29:52.575274       1 csvprovider.go:284] storage capacity = 5Gi``

**Comment by scottkarnold** [comment]
Hi Michael,
Thanks for looking at my PR.  I have updated the PR comments with the steps I performed to test the change.
    On Thursday, February 25, 2021, 10:00:13 AM EST, Michael Dresser <notifications@github.com> wrote:  
 
 


Hi @scottkarnold, thanks for opening up a PR! From a first glance it doesn't look too controversial.

Could you add a comment explaining how you tested this change?

**Comment by michaelmdresser** [comment]
Looks great, thanks for the details.

**Review by michaelmdresser — APPROVED** [review]

**Comment by AjayTripathy** [comment]
Thank you so much for this PR @scottkarnold !

**Pull request merged**
