### PR TITLE
fix indexing error for updated GCP API

### PR DESCRIPTION
**Pull request by AjayTripathy**
Fix error caused by change in the GCP pricing API.

### CODE REVIEW

**Comment by AjayTripathy** [comment]
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/kubecost/cost-model/pkg/cloud.(*GCP).parsePage(0xc0000ce480, 0x7fe8cc548988, 0xc000596120, 0xc00069ed08, 0xc00069ed38, 0x0, 0xc000000000, 0xc0002777a0, 0x38298cd, 0xe)
	/app/cost-model/pkg/cloud/gcpprovider.go:648 +0x3a2c
github.com/kubecost/cost-model/pkg/cloud.(*GCP).parsePages.func1(0x0, 0x0, 0x2337d5a, 0x23)
	/app/cost-model/pkg/cloud/gcpprovider.go:906 +0x127
github.com/kubecost/cost-model/pkg/cloud.(*GCP).parsePages(0xc0000ce480, 0xc000628d08, 0xc000628d38, 0x2b, 0xc000628cb8, 0x1)
	/app/cost-model/pkg/cloud/gcpprovider.go:913 +0x21c
github.com/kubecost/cost-model/pkg/cloud.(*GCP).DownloadPricingData(0xc0000ce480, 0x0, 0x0)
	/app/cost-model/pkg/cloud/gcpprovider.go:1014 +0xd9a
github.com/kubecost/cost-model/pkg/costmodel.Initialize(0xc000348720, 0x4, 0x4, 0x20fe2a0)
	/app/cost-model/pkg/costmodel/router.go:1045 +0x15c6
main.Initialize(0x2)
	/app/kubecost-cost-model/main.go:3004 +0xd9
main.main()
	/app/kubecost-cost-model/main.go:3155 +0x37

**Comment by michaelmdresser** [comment]
Builds on https://github.com/kubecost/cost-model/pull/717

**Comment by michaelmdresser** [comment]
This error occurs whenever `DownloadPricingData` is called. On pod start, new node type (e.g. new node pool), potentially other cases.

**Review by michaelmdresser — APPROVED** [review]
Appears to cover all of the cases this will be an issue in. This should be revisited to handle better.

**Review by nikovacevic — APPROVED** [review]

**Pull request merged**
